name: Diagonalize

# Controls when the workflow will run
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    # schedule for 3:00am CST which is 9:00am UTC
    - cron:  '0 9 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Diagonalize-matrices:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        NOISE: [5,10,20,50,100]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install python dependencies/packages
        run: |
          python -m pip install --upgrade pip
          pip3 install numpy matplotlib
      - name: Diagonalize matrix with noise [${{ matrix.NOISE }}]
        run: |
          echo "This will diagonalize a matrix with a given noise."
          echo "Noise = $NOISE"
          python diagonalize_matrix_with_noise.py -f $FILENAME -W $NOISE
